# -*- coding: utf-8 -*-
# Genera secciones.json (maestro en ESPAÑOL) a partir del contenido curado de las
# infografías de la carpeta "imagenes comida/". Los platos que solo traían nombre
# o ingredientes se han completado con preparación paso a paso (conocimiento
# culinario estándar; cantidades orientativas para 2 raciones).
#
# El esquema es deliberadamente simple: {id, title, ingredients[], instructions}.
# La app calcula alérgenos y compatibilidad de dieta a partir del texto de los
# ingredientes con el MISMO motor que el resto del recetario (allergensOfText /
# DIET_BLOCKERS en app.js), así no hay etiquetas duplicadas que mantener.
#
# Uso:  python3 build_secciones.py   ->  escribe secciones.json
import json

SECCIONES = []

def seccion(sid, titulo, icon, descripcion, platos):
    SECCIONES.append({
        "id": sid, "titulo": titulo, "icon": icon,
        "descripcion": descripcion, "platos": platos,
    })

def p(pid, title, ingredients, instructions, **extra):
    d = {"id": pid, "title": title, "ingredients": ingredients, "instructions": instructions}
    d.update(extra)
    return d

# ===========================================================================
# 1) SOPAS FRÍAS ESPAÑOLAS  (img 8 — traían ingredientes)
# ===========================================================================
seccion("sopas-frias", "Sopas frías españolas", "ac_unit",
    "Seis clásicos refrescantes para el verano, listos en la batidora.", [
    p("sf-gazpacho-andaluz", "Gazpacho andaluz",
      ["1 kg de tomates maduros", "1/2 pepino", "1 pimiento verde italiano",
       "1 diente de ajo", "50 g de pan del día anterior", "50 ml de aceite de oliva virgen extra",
       "1 cucharada de vinagre de vino", "sal al gusto"],
      "Trocea los tomates, el pepino y el pimiento y ponlos en el vaso de la batidora con el ajo y el pan remojado. Tritura hasta que quede fino y, con la máquina en marcha, añade el aceite en hilo para que emulsione. Ajusta de vinagre y sal, cuela si lo quieres muy fino y enfría al menos 2 horas antes de servir."),
    p("sf-salmorejo-cordobes", "Salmorejo cordobés",
      ["1 kg de tomates maduros", "150 g de pan blanco del día anterior", "1 diente de ajo",
       "100 ml de aceite de oliva virgen extra", "sal al gusto",
       "2 huevos duros y 50 g de jamón serrano para servir"],
      "Tritura los tomates con el ajo y la sal, añade el pan en trozos y deja que se hidrate un par de minutos. Vuelve a triturar incorporando el aceite poco a poco hasta lograr una crema espesa y anaranjada. Enfría y sirve con huevo duro picado y jamón por encima."),
    p("sf-ajoblanco-malagueno", "Ajoblanco malagueño",
      ["150 g de almendras crudas peladas", "1 diente de ajo", "50 g de pan del día anterior",
       "60 ml de aceite de oliva virgen extra", "1 cucharada de vinagre", "750 ml de agua fría",
       "sal al gusto", "uvas o melón para servir"],
      "Remoja el pan y tritúralo con las almendras, el ajo y un poco de agua hasta obtener una pasta. Añade el resto del agua, el vinagre y la sal, y emulsiona con el aceite en hilo hasta que quede sedoso. Sirve muy frío con unas uvas partidas por encima."),
    p("sf-porra-antequerana", "Porra antequerana",
      ["1 kg de tomates maduros", "200 g de pan del día anterior", "1 diente de ajo",
       "1 pimiento verde pequeño", "120 ml de aceite de oliva virgen extra", "sal al gusto",
       "huevo duro y jamón para servir"],
      "Tritura los tomates con el ajo, el pimiento y la sal, incorpora el pan remojado y deja reposar. Bate de nuevo emulsionando con el aceite hasta una crema más espesa que el gazpacho. Sirve fría con huevo duro y taquitos de jamón."),
    p("sf-gazpacho-verde", "Gazpacho verde",
      ["1 pepino", "1 pimiento verde", "1 manzana verde", "1/2 aguacate", "1 puñado de espinacas",
       "40 ml de aceite de oliva virgen extra", "el zumo de 1 lima", "200 ml de agua fría", "sal al gusto"],
      "Pela y trocea el pepino, la manzana y el aguacate y ponlos en la batidora con el pimiento y las espinacas. Tritura con el agua y la lima hasta que quede una crema verde y fina, emulsionando con el aceite. Rectifica de sal y sirve bien frío."),
    p("sf-gazpacho-sandia", "Gazpacho de sandía",
      ["500 g de sandía sin pepitas", "2 tomates maduros", "1/2 pepino",
       "30 ml de aceite de oliva virgen extra", "1 cucharadita de vinagre", "unas hojas de menta", "sal al gusto"],
      "Tritura la sandía con el tomate y el pepino hasta que quede líquido. Emulsiona con el aceite y el vinagre, añade unas hojas de menta y sal, y vuelve a batir. Cuela y sirve muy frío; queda dulce y refrescante."),
])

# ===========================================================================
# 2) SALSAS CASERAS  (img 6 — traían ingredientes)
# ===========================================================================
seccion("salsas", "Salsas caseras", "blender",
    "Seis salsas para acompañar carnes, verduras, ensaladas y picoteo.", [
    p("salsa-ranch", "Salsa ranch",
      ["4 cucharadas de mayonesa", "3 cucharadas de yogur natural o nata agria", "2 cucharadas de leche",
       "1/2 cucharadita de ajo en polvo", "1/2 cucharadita de cebolla en polvo", "1 cucharada de cebollino picado",
       "1 cucharadita de eneldo", "sal y pimienta"],
      "Mezcla la mayonesa con el yogur y la leche hasta que quede una crema fluida. Añade el ajo y la cebolla en polvo, el cebollino y el eneldo, y salpimienta. Deja reposar 30 minutos en frío para que se integren los sabores."),
    p("salsa-bufalo", "Salsa búfalo",
      ["120 ml de salsa picante tipo cayena (hot sauce)", "60 g de mantequilla",
       "1 cucharadita de vinagre", "1/2 cucharadita de ajo en polvo", "una pizca de sal"],
      "Derrite la mantequilla a fuego suave y retírala del fuego. Añade la salsa picante, el vinagre y el ajo en polvo y bate hasta que emulsione y quede brillante. Úsala templada sobre alitas o coliflor asada."),
    p("salsa-tartara", "Salsa tártara",
      ["6 cucharadas de mayonesa", "2 pepinillos en vinagre picados", "1 cucharada de alcaparras picadas",
       "1/2 cebolla pequeña muy picada", "1 cucharada de perejil", "1 cucharadita de mostaza", "unas gotas de limón"],
      "Pica muy finos los pepinillos, las alcaparras y la cebolla. Mézclalos con la mayonesa, la mostaza, el perejil y el limón. Enfría antes de servir; acompaña pescados y frituras."),
    p("salsa-alfredo", "Salsa alfredo",
      ["250 ml de nata para cocinar", "50 g de mantequilla", "80 g de queso parmesano rallado",
       "1 diente de ajo", "una pizca de nuez moscada", "sal y pimienta"],
      "Funde la mantequilla con el ajo picado sin que se dore. Añade la nata y calienta sin que hierva, incorpora el parmesano poco a poco removiendo hasta que espese. Sazona con nuez moscada, sal y pimienta y usa enseguida sobre pasta."),
    p("salsa-chipotle", "Salsa de chipotle",
      ["6 cucharadas de mayonesa", "2 chiles chipotle en adobo", "1 cucharada de la salsa de adobo",
       "el zumo de 1/2 lima", "1/2 diente de ajo", "sal"],
      "Tritura los chipotles con su adobo, el ajo y la lima hasta obtener una pasta. Mézclala con la mayonesa hasta lograr el punto de picante que prefieras. Refrigera; va bien con tacos, hamburguesas y patatas."),
    p("salsa-yogur-pepino", "Salsa de yogur y pepino (tzatziki)",
      ["250 g de yogur griego", "1/2 pepino rallado y escurrido", "1 diente de ajo",
       "1 cucharada de aceite de oliva", "unas hojas de menta o eneldo", "el zumo de 1/2 limón", "sal"],
      "Ralla el pepino, sálalo y escúrrelo bien para quitar el agua. Mézclalo con el yogur, el ajo machacado, el aceite, el limón y la hierba picada. Enfría 1 hora; refresca carnes a la parrilla y verduras."),
])

# ===========================================================================
# 3) BEBIDAS SALUDABLES / SMOOTHIES  (img 3 — RO, traían ingredientes)
# ===========================================================================
seccion("smoothies", "Bebidas saludables y smoothies", "local_bar",
    "Diez batidos nutritivos para el desayuno o la merienda. Tritura todo bien frío.", [
    p("sm-arandanos", "Smoothie de arándanos",
      ["150 g de arándanos", "1 plátano", "200 ml de leche o bebida vegetal",
       "1 cucharada de copos de avena", "1 cucharadita de miel"],
      "Pon todos los ingredientes en la batidora. Tritura hasta que quede homogéneo y cremoso. Sirve al momento; si lo quieres más líquido añade un poco más de leche."),
    p("sm-chocolate", "Smoothie de chocolate",
      ["1 plátano congelado", "200 ml de leche o bebida vegetal", "1 cucharada de cacao puro en polvo",
       "1 cucharada de mantequilla de cacahuete", "1 dátil opcional"],
      "Tritura el plátano con la leche, el cacao y la mantequilla de cacahuete. Bate hasta que quede espeso y sin grumos. Endulza con el dátil si lo necesitas."),
    p("sm-melocoton", "Smoothie de melocotón",
      ["2 melocotones maduros", "150 g de yogur natural", "150 ml de leche", "1 cucharadita de miel"],
      "Pela y trocea los melocotones. Tritúralos con el yogur, la leche y la miel hasta que quede suave. Sirve frío."),
    p("sm-vainilla", "Smoothie de vainilla",
      ["1 plátano", "200 ml de leche", "150 g de yogur", "1/2 cucharadita de extracto de vainilla",
       "1 cucharadita de miel"],
      "Bate el plátano con el yogur, la leche, la vainilla y la miel. Tritura hasta lograr una textura de batido cremoso. Sirve enseguida."),
    p("sm-verde", "Smoothie verde",
      ["1 puñado de espinacas", "1 manzana verde", "1 plátano", "200 ml de agua o bebida vegetal",
       "un trocito de jengibre", "el zumo de 1/2 limón"],
      "Lava las espinacas y trocea la fruta. Tritura todo con el agua, el jengibre y el limón hasta que quede fino y sin hebras. Bebe recién hecho para aprovechar las vitaminas."),
    p("sm-fresa", "Smoothie de fresa",
      ["200 g de fresas", "150 g de yogur", "150 ml de leche", "1 cucharadita de miel"],
      "Lava y despunta las fresas. Tritúralas con el yogur, la leche y la miel hasta que quede rosado y espumoso. Sirve frío."),
    p("sm-platano", "Smoothie de plátano y avena",
      ["2 plátanos", "250 ml de leche o bebida vegetal", "2 cucharadas de copos de avena",
       "1/2 cucharadita de canela", "1 cucharadita de miel"],
      "Tritura los plátanos con la leche, la avena y la canela. Bate bien hasta que la avena se integre y quede cremoso. Es saciante, ideal antes de entrenar."),
    p("sm-mango", "Smoothie de mango",
      ["1 mango maduro", "150 g de yogur", "100 ml de zumo de naranja", "1 cucharadita de miel"],
      "Pela y trocea el mango. Tritúralo con el yogur, el zumo de naranja y la miel hasta que quede tropical y suave. Sirve muy frío."),
    p("sm-sandia", "Smoothie de sandía",
      ["400 g de sandía sin pepitas", "100 g de fresas", "el zumo de 1 lima", "unas hojas de menta", "hielo"],
      "Tritura la sandía con las fresas, la lima y la menta. Añade hielo y bate hasta que quede granizado. Muy refrescante y bajo en calorías."),
    p("sm-pina", "Smoothie de piña y coco",
      ["200 g de piña", "1 plátano", "150 ml de leche de coco", "100 ml de agua"],
      "Trocea la piña y el plátano. Tritúralos con la leche de coco y el agua hasta que quede una bebida tipo piña colada sin alcohol. Sirve con hielo."),
])

# ===========================================================================
# 4) COMIDAS PROTEICAS PARA LLEVAR  (img 1 — NutriGlow, con macros)
# ===========================================================================
seccion("comidas-proteicas", "Comidas proteicas para llevar", "fitness_center",
    "Cinco fiambreras frescas y altas en proteína, ideales para la playa o la oficina.", [
    p("pl-ensalada-atun-garbanzos", "Ensalada de atún y garbanzos",
      ["1 lata grande de atún al natural", "250 g de garbanzos cocidos", "1 tomate",
       "1/2 cebolla roja", "1 huevo duro", "perejil", "aceite de oliva, vinagre y sal"],
      "Escurre los garbanzos y el atún y mézclalos con el tomate y la cebolla picados. Aliña con aceite, vinagre, sal y perejil, y corona con el huevo duro en gajos. Aguanta perfectamente en fiambrera. Aporta unos 32 g de proteína."),
    p("pl-wrap-pollo-aguacate", "Wrap de pollo y aguacate",
      ["1 tortilla de trigo grande", "150 g de pollo a la plancha en tiras", "1/2 aguacate",
       "hojas de lechuga", "1 tomate en rodajas", "1 cucharada de yogur o salsa ligera"],
      "Unta la tortilla con el yogur y reparte la lechuga, el tomate, el aguacate laminado y el pollo. Enrolla apretando bien y envuelve en papel para transportarlo. Aporta unos 38 g de proteína."),
    p("pl-pasta-pollo-pesto", "Pasta fría con pollo y pesto",
      ["180 g de pasta corta", "150 g de pollo cocido", "2 cucharadas de pesto",
       "8 tomates cherry", "30 g de queso parmesano", "rúcula"],
      "Cuece la pasta al dente y enfríala bajo el grifo. Mézclala con el pesto, el pollo desmenuzado, los cherry partidos y la rúcula, y reparte el parmesano. Se come fría y aporta unos 36 g de proteína."),
    p("pl-bowl-quinoa-salmon", "Bowl de quinoa y salmón",
      ["120 g de quinoa", "150 g de salmón cocido o a la plancha", "1/2 aguacate", "1 zanahoria rallada",
       "un puñado de edamame", "salsa de soja y sésamo"],
      "Cuece la quinoa y déjala enfriar. Móntala en el bowl con el salmón, el aguacate, la zanahoria y el edamame, y aliña con soja y sésamo. Aporta unos 29 g de proteína."),
    p("pl-hummus-verduras-huevo", "Hummus con verduras y huevo",
      ["150 g de hummus", "1 zanahoria en bastones", "1/2 pepino en bastones",
       "1 pimiento en tiras", "2 huevos duros", "picos de pan integral"],
      "Coloca el hummus en el centro y reparte alrededor las verduras crudas en bastones. Añade los huevos duros partidos y unos picos para mojar. Aporta unos 22 g de proteína."),
])

# ===========================================================================
# 5) TAPAS Y PINTXOS VASCOS  (img 1 pintxos — solo nombres, preparación redactada)
# ===========================================================================
seccion("pintxos", "Pintxos vascos", "tapas",
    "Quince pintxos clásicos del norte: bocados pequeños de gran sabor.", [
    p("px-gilda", "Gilda clásica",
      ["3 aceitunas verdes sin hueso", "2 anchoas en aceite", "2 guindillas en vinagre (piparras)",
       "aceite de oliva virgen extra"],
      "Ensarta en un palillo una aceituna, una guindilla enrollada y una anchoa, repitiendo hasta montar el pintxo. Riega con un hilo de aceite de oliva. Se sirve frío como aperitivo salado y picante."),
    p("px-tortilla-cremosa", "Tortilla cremosa de patata",
      ["3 huevos", "2 patatas medianas", "1/2 cebolla", "aceite de oliva", "sal", "pan en rebanadas"],
      "Fríe a fuego suave las patatas y la cebolla en láminas hasta que estén tiernas y escúrrelas. Mézclalas con los huevos batidos y cuaja la tortilla dejándola jugosa por dentro. Sirve un trozo sobre pan."),
    p("px-anchoa-piparra", "Anchoa y piparra",
      ["2 anchoas en aceite", "2 piparras en vinagre", "1 rebanada de pan", "tomate rallado", "aceite de oliva"],
      "Unta el pan con un poco de tomate rallado y aceite. Coloca encima las anchoas y acompaña con las piparras. Bocado salino y fresco a la vez."),
    p("px-bacalao-pilpil", "Bacalao al pil pil",
      ["200 g de bacalao desalado", "3 dientes de ajo", "1 guindilla", "100 ml de aceite de oliva", "pan"],
      "Confita los ajos y la guindilla en el aceite y retíralos. Cocina el bacalao a fuego muy suave por el lado de la piel y, fuera del fuego, mueve la cazuela en círculos para ligar el pil pil con la gelatina del pescado. Sirve sobre pan."),
    p("px-jamon-brie", "Jamón ibérico y brie",
      ["50 g de jamón ibérico", "50 g de queso brie", "1 rebanada de pan", "mermelada o membrillo"],
      "Tuesta ligeramente el pan y coloca una loncha de brie. Pon encima el jamón ibérico y un toque de mermelada. El contraste de salado y dulce es la clave."),
    p("px-pulpo-gallega", "Pulpo a la gallega",
      ["200 g de pulpo cocido", "1 patata cocida", "pimentón dulce y picante", "sal en escamas", "aceite de oliva"],
      "Corta el pulpo en rodajas y colócalo sobre una rodaja de patata cocida. Espolvorea pimentón y sal en escamas y riega con aceite de oliva. Sirve templado."),
    p("px-txaka", "Txaka (ensaladilla de surimi)",
      ["150 g de surimi", "3 cucharadas de mayonesa", "1 cucharada de tomate frito", "unas gotas de brandy", "pan"],
      "Desmenuza el surimi y mézclalo con la mayonesa y el tomate frito hasta lograr una crema rosada. Añade unas gotas de brandy. Sirve sobre pan o en tartaleta."),
    p("px-croquetas", "Croquetas caseras de jamón",
      ["50 g de jamón serrano", "40 g de mantequilla", "40 g de harina", "400 ml de leche",
       "1 huevo", "pan rallado", "aceite para freír", "nuez moscada y sal"],
      "Haz una bechamel espesa con la mantequilla, la harina y la leche, añade el jamón picado y la nuez moscada y deja enfriar. Forma las croquetas, pásalas por huevo y pan rallado y fríelas en aceite caliente hasta dorar."),
    p("px-boqueron-donostiarra", "Boquerones en vinagre",
      ["200 g de boquerones limpios", "vinagre de vino", "2 dientes de ajo", "perejil", "aceite de oliva", "sal"],
      "Cubre los boquerones abiertos con vinagre y sal y déjalos macerar unas horas en frío hasta que blanqueen. Escúrrelos y alíñalos con ajo y perejil picados y abundante aceite de oliva. Sirve muy fríos sobre pan."),
    p("px-solomillo-foie", "Solomillo y foie",
      ["150 g de solomillo de ternera", "50 g de foie", "1 rebanada de pan", "reducción de Pedro Ximénez", "sal y pimienta"],
      "Marca el solomillo a la plancha al punto y salpiméntalo. Sella el foie unos segundos por cada lado y móntalo sobre el solomillo y el pan. Termina con un hilo de reducción de Pedro Ximénez."),
    p("px-txangurro", "Txangurro gratinado",
      ["200 g de carne de centollo o cangrejo", "1/2 cebolla", "1 tomate", "un chorrito de brandy",
       "pan rallado", "mantequilla"],
      "Pocha la cebolla y el tomate, añade la carne de centollo y el brandy y deja reducir. Rellena las conchas o cazuelitas, espolvorea pan rallado con unas láminas de mantequilla y gratina hasta dorar."),
    p("px-atun-cebolla", "Atún rojo y cebolla confitada",
      ["150 g de atún rojo", "1 cebolla", "1 cucharada de azúcar moreno", "vinagre", "aceite de oliva", "sal"],
      "Confita la cebolla en juliana a fuego lento con un poco de azúcar y vinagre hasta caramelizar. Marca el atún por fuera dejándolo crudo en el centro y córtalo en tacos. Sirve sobre la cebolla y pan."),
    p("px-morcilla-piquillos", "Morcilla y piquillos",
      ["150 g de morcilla de Burgos", "2 pimientos del piquillo", "1 rebanada de pan", "aceite de oliva"],
      "Fríe la morcilla desmenuzada hasta que quede suelta y crujiente. Calienta los piquillos en la misma sartén. Monta sobre el pan la morcilla y los piquillos encima."),
    p("px-salmon-ahumado", "Salmón ahumado y queso crema",
      ["80 g de salmón ahumado", "2 cucharadas de queso crema", "1 rebanada de pan", "eneldo", "alcaparras"],
      "Unta el pan con el queso crema y coloca el salmón ahumado en pliegues. Decora con eneldo y unas alcaparras. Pintxo fresco que no necesita cocción."),
    p("px-cangrejos-vino", "Cangrejos al vino (changurro)",
      ["200 g de carne de cangrejo", "1/2 cebolla", "1 tomate", "100 ml de vino blanco",
       "aceite de oliva", "perejil", "sal"],
      "Sofríe la cebolla y el tomate, añade la carne de cangrejo y riega con el vino blanco. Deja reducir hasta que el sofrito quede meloso y reparte perejil. Sirve caliente en cazuelita o sobre pan."),
])

# ===========================================================================
# 6) TOSTAS Y TARTINES SALADAS  (img 2 — FR, solo nombres, preparación redactada)
# ===========================================================================
seccion("tostas", "Tostas y tartines saladas", "lunch_dining",
    "Veinticinco ideas de tostas saladas, fáciles y rápidas de montar sobre buen pan.", [
    p("ts-aguacate-huevo", "Tosta de aguacate y huevo poché",
      ["1 rebanada de pan rústico", "1/2 aguacate", "1 huevo", "vinagre", "sal en escamas", "pimienta"],
      "Tuesta el pan y aplasta encima el aguacate con sal. Escalfa el huevo en agua con un chorro de vinagre 3 minutos y colócalo sobre el aguacate. Termina con sal en escamas y pimienta."),
    p("ts-jamon-burrata", "Tosta de jamón crudo, burrata y tomate",
      ["1 rebanada de pan", "1/2 burrata", "2 lonchas de jamón serrano", "1 tomate", "albahaca", "aceite de oliva"],
      "Coloca la burrata abierta sobre el pan y reparte el tomate en rodajas. Añade el jamón y unas hojas de albahaca y riega con aceite. Sirve enseguida para que la burrata esté cremosa."),
    p("ts-salmon-aguacate", "Tosta de salmón ahumado y aguacate",
      ["1 rebanada de pan", "1/2 aguacate", "60 g de salmón ahumado", "queso crema", "eneldo", "limón"],
      "Unta el pan con queso crema y extiende el aguacate laminado. Coloca el salmón en pliegues y termina con eneldo y unas gotas de limón."),
    p("ts-cabra-miel", "Tosta de queso de cabra y miel",
      ["1 rebanada de pan", "1 rodaja de rulo de cabra", "1 cucharadita de miel", "nueces", "tomillo"],
      "Coloca el queso sobre el pan y gratínalo unos minutos hasta que se dore. Riega con miel y reparte nueces troceadas y tomillo. Sirve templado."),
    p("ts-atun-rabano", "Tosta de atún, mayonesa y rábano",
      ["1 rebanada de pan", "1 lata de atún", "1 cucharada de mayonesa", "2 rábanos", "cebollino"],
      "Mezcla el atún escurrido con la mayonesa y extiéndelo sobre el pan. Cubre con rábanos en láminas finas y cebollino picado."),
    p("ts-caprese", "Tosta caprese",
      ["1 rebanada de pan", "1/2 bola de mozzarella", "1 tomate", "albahaca", "aceite de oliva", "sal"],
      "Reparte sobre el pan rodajas de mozzarella y tomate alternadas. Añade hojas de albahaca, sal y un hilo de aceite. Fresca y mediterránea."),
    p("ts-salmon-eneldo", "Tosta de salmón y eneldo",
      ["1 rebanada de pan de centeno", "60 g de salmón ahumado", "queso crema", "eneldo", "pepino"],
      "Unta el pan de centeno con queso crema y coloca láminas de pepino. Añade el salmón y abundante eneldo fresco."),
    p("ts-jamon-emmental", "Tosta de jamón cocido y emmental",
      ["1 rebanada de pan", "2 lonchas de jamón cocido", "2 lonchas de emmental", "mostaza suave"],
      "Unta el pan con mostaza y coloca el jamón cocido y el emmental. Hornea o gratina hasta que el queso se funda."),
    p("ts-chorizo-manchego", "Tosta de chorizo y queso manchego",
      ["1 rebanada de pan", "4 rodajas de chorizo", "2 lonchas de queso manchego", "aceite de oliva"],
      "Fríe ligeramente el chorizo para que suelte su grasa. Móntalo sobre el pan con el manchego y un hilo de aceite. Calienta hasta que el queso empiece a fundirse."),
    p("ts-guacamole-gambas", "Tosta de guacamole y gambas",
      ["1 rebanada de pan", "1/2 aguacate", "6 gambas peladas", "lima", "cilantro", "ajo"],
      "Machaca el aguacate con lima, sal y cilantro y extiéndelo sobre el pan. Saltea las gambas con un poco de ajo y colócalas encima."),
    p("ts-pate-pepinillos", "Tosta de paté y pepinillos",
      ["1 rebanada de pan", "50 g de paté", "2 pepinillos", "cebolla encurtida"],
      "Unta el pan con el paté. Cubre con pepinillos en láminas y un poco de cebolla encurtida para cortar la grasa."),
    p("ts-queso-fresco-pepino", "Tosta de queso fresco, pepino y eneldo",
      ["1 rebanada de pan", "3 cucharadas de queso fresco batido", "1/2 pepino", "eneldo", "sal"],
      "Extiende el queso fresco sobre el pan. Cubre con láminas de pepino, eneldo y una pizca de sal. Ligera y refrescante."),
    p("ts-brie-pera-nueces", "Tosta de brie, pera y nueces",
      ["1 rebanada de pan", "2 lonchas de brie", "1/2 pera", "nueces", "miel"],
      "Coloca el brie sobre el pan y la pera laminada encima. Reparte nueces y un hilo de miel y gratina ligeramente."),
    p("ts-hummus-verduras", "Tosta de hummus y verduras asadas",
      ["1 rebanada de pan", "3 cucharadas de hummus", "calabacín y pimiento asados", "sésamo"],
      "Unta el pan con hummus generosamente. Coloca encima las verduras asadas templadas y espolvorea sésamo."),
    p("ts-sardinas-tomate", "Tosta de sardinas y tomate",
      ["1 rebanada de pan", "1 lata de sardinas", "tomate rallado", "aceite de oliva", "sal"],
      "Unta el pan con tomate rallado y aceite. Coloca las sardinas escurridas encima y una pizca de sal."),
    p("ts-ricotta-miel-nueces", "Tosta de ricotta, miel y nueces",
      ["1 rebanada de pan", "3 cucharadas de ricotta", "1 cucharadita de miel", "nueces", "canela"],
      "Extiende la ricotta sobre el pan tostado. Riega con miel y reparte nueces y un toque de canela. Dulce y salada a la vez."),
    p("ts-pavo-mostaza", "Tosta de pavo, lechuga y mostaza",
      ["1 rebanada de pan", "2 lonchas de pechuga de pavo", "hojas de lechuga", "mostaza", "tomate"],
      "Unta el pan con mostaza y coloca la lechuga, el tomate y el pavo. Opción ligera y rápida para media mañana."),
    p("ts-azul-higo", "Tosta de queso azul, higo y nueces",
      ["1 rebanada de pan", "30 g de queso azul", "1 higo", "nueces", "miel"],
      "Reparte el queso azul desmenuzado sobre el pan. Añade el higo en gajos, nueces y un hilo de miel para equilibrar el sabor fuerte del queso."),
    p("ts-pan-tumaca", "Pan con tomate (pa amb tomàquet)",
      ["1 rebanada de pan", "1 tomate maduro", "1 diente de ajo", "aceite de oliva virgen extra", "sal"],
      "Tuesta el pan y frótalo con el ajo y luego con el tomate partido. Riega con buen aceite y sal. La base del picoteo mediterráneo."),
    p("ts-boquerones-pimiento", "Tosta de boquerones y pimiento asado",
      ["1 rebanada de pan", "3 boquerones en vinagre", "1/2 pimiento rojo asado", "aceite de oliva"],
      "Coloca tiras de pimiento asado sobre el pan. Añade los boquerones en vinagre y un hilo de aceite."),
    p("ts-queso-crema-salmon", "Tosta de queso crema y salmón",
      ["1 rebanada de pan", "2 cucharadas de queso crema", "60 g de salmón ahumado", "alcaparras", "cebolla roja"],
      "Unta el queso crema y coloca el salmón. Termina con alcaparras y cebolla roja en aros finos."),
    p("ts-revuelto-champinones", "Tosta de revuelto de champiñones",
      ["1 rebanada de pan", "100 g de champiñones", "1 huevo", "ajo", "perejil", "aceite"],
      "Saltea los champiñones laminados con ajo hasta dorar y añade el huevo para hacer un revuelto jugoso. Reparte sobre el pan con perejil."),
    p("ts-berenjena-feta", "Tosta de berenjena asada y feta",
      ["1 rebanada de pan", "1/2 berenjena", "40 g de queso feta", "menta", "aceite de oliva"],
      "Asa la berenjena en rodajas con aceite hasta que esté tierna. Colócala sobre el pan con feta desmenuzado y menta."),
    p("ts-anchoas-mantequilla", "Tosta de anchoas y mantequilla",
      ["1 rebanada de pan", "3 anchoas en aceite", "mantequilla", "cebollino"],
      "Unta el pan con una capa de mantequilla. Coloca las anchoas encima y espolvorea cebollino. Un clásico francés sencillo."),
    p("ts-tortilla-jamon", "Tosta de tortilla francesa y jamón",
      ["1 rebanada de pan", "2 huevos", "2 lonchas de jamón cocido", "aceite", "sal"],
      "Haz una tortilla francesa jugosa y dóblala sobre el pan. Añade el jamón y una pizca de sal."),
])

# ===========================================================================
# 7) APERITIVOS SIMPLES  (img 5 — FR, solo nombres, preparación redactada)
# ===========================================================================
seccion("aperitivos", "Aperitivos para picar", "celebration",
    "Veinte aperitivos sencillos que siempre triunfan en una reunión.", [
    p("ap-brocheta-caprese", "Brochetas de tomate y mozzarella",
      ["12 tomates cherry", "12 mini mozzarellas", "albahaca", "aceite de oliva", "vinagre balsámico"],
      "Ensarta en palillos un cherry, una hoja de albahaca y una mozzarella. Aliña con aceite y un toque de balsámico. Listo en minutos."),
    p("ap-rollitos-calabacin", "Rollitos de calabacín y queso crema",
      ["1 calabacín", "100 g de queso crema", "menta", "aceite de oliva", "sal"],
      "Corta el calabacín en láminas finas a lo largo y márcalas en la plancha. Unta con queso crema y menta, enrolla y sujeta con un palillo."),
    p("ap-huevos-rellenos", "Huevos rellenos",
      ["4 huevos duros", "1 lata de atún", "2 cucharadas de mayonesa", "tomate frito", "aceitunas"],
      "Parte los huevos por la mitad y mezcla las yemas con el atún y la mayonesa. Rellena las claras con la pasta y decora con un poco de tomate frito y aceituna."),
    p("ap-mini-quiches", "Mini quiches de verduras",
      ["1 lámina de masa quebrada", "2 huevos", "100 ml de nata", "puerro y espinacas", "queso rallado", "sal"],
      "Forra moldes de magdalena con la masa. Rellena con la verdura pochada y la mezcla de huevo, nata y queso, y hornea a 180 °C unos 20 minutos."),
    p("ap-tartaletas-tomate", "Tartaletas de tomate y queso",
      ["8 tartaletas", "tomate frito", "queso rallado", "orégano"],
      "Rellena las tartaletas con tomate y queso. Gratina hasta que el queso se funda y espolvorea orégano."),
    p("ap-brocheta-melon-jamon", "Brochetas de melón y jamón",
      ["1/4 de melón", "8 lonchas de jamón serrano", "menta"],
      "Corta el melón en dados y envuélvelos con media loncha de jamón. Ensarta en palillos con una hoja de menta. Dulce y salado."),
    p("ap-palmeritas-pesto", "Palmeritas de hojaldre y pesto",
      ["1 lámina de hojaldre", "3 cucharadas de pesto", "queso parmesano"],
      "Extiende el pesto sobre el hojaldre y enrolla los dos lados hacia el centro. Corta en rodajas, espolvorea parmesano y hornea hasta dorar."),
    p("ap-champinones-rellenos", "Champiñones rellenos",
      ["12 champiñones grandes", "100 g de queso crema", "ajo", "perejil", "pan rallado"],
      "Retira los pies de los champiñones y pícalos. Mézclalos con queso crema, ajo y perejil, rellena los sombreros, espolvorea pan rallado y hornea 15 minutos."),
    p("ap-bolitas-queso", "Bolitas de queso y hierbas",
      ["200 g de queso crema", "50 g de queso rallado", "hierbas frescas", "frutos secos picados"],
      "Mezcla los quesos y forma bolitas con las manos. Rebózalas en hierbas y frutos secos picados y enfría hasta servir."),
    p("ap-brocheta-pollo-pina", "Brochetas de pollo y piña",
      ["1 pechuga de pollo", "200 g de piña", "salsa de soja", "miel", "sésamo"],
      "Marina el pollo en dados con soja y miel. Ensártalo alternando con piña y cocínalo a la plancha; espolvorea sésamo."),
    p("ap-cherry-atun", "Tomates cherry rellenos de atún",
      ["16 tomates cherry grandes", "1 lata de atún", "2 cucharadas de mayonesa", "cebollino"],
      "Vacía los cherry con cuidado. Rellénalos con atún mezclado con mayonesa y termina con cebollino."),
    p("ap-rollitos-salmon", "Rollitos de salmón y queso",
      ["100 g de salmón ahumado", "100 g de queso crema", "eneldo"],
      "Extiende las lonchas de salmón, unta queso crema con eneldo y enróllalas. Corta en rodajas tipo sushi."),
    p("ap-crackers-pate", "Crackers con paté y pepinillo",
      ["12 crackers", "100 g de paté", "pepinillos"],
      "Unta cada cracker con paté. Corona con una lámina de pepinillo. Rápido y resultón."),
    p("ap-datiles-bacon", "Dátiles envueltos en bacon",
      ["12 dátiles sin hueso", "6 lonchas de bacon", "almendras"],
      "Rellena cada dátil con una almendra y envuélvelo con media loncha de bacon. Hornea hasta que el bacon esté crujiente."),
    p("ap-bruschetta-tomate", "Mini bruschettas de tomate",
      ["1 baguette", "2 tomates", "albahaca", "ajo", "aceite de oliva", "sal"],
      "Tuesta rodajas de baguette y frótalas con ajo. Cubre con tomate picado aliñado con albahaca, aceite y sal."),
    p("ap-pinchos-caprese", "Pinchos caprese",
      ["12 tomates cherry", "12 bolitas de mozzarella", "albahaca", "balsámico"],
      "Alterna en cada palillo cherry, albahaca y mozzarella. Riega con una reducción de balsámico."),
    p("ap-pepino-feta", "Pinchos de pepino y feta",
      ["1 pepino", "100 g de queso feta", "aceitunas negras", "orégano"],
      "Corta el pepino en rodajas gruesas y coloca encima un dado de feta y media aceituna. Sujeta con palillo y espolvorea orégano."),
    p("ap-croquetas-jamon", "Croquetas de jamón",
      ["bechamel espesa con 50 g de jamón", "huevo", "pan rallado", "aceite para freír"],
      "Forma las croquetas con la masa de bechamel y jamón ya fría. Rebózalas en huevo y pan rallado y fríelas hasta dorar."),
    p("ap-aceitunas-marinadas", "Aceitunas marinadas",
      ["250 g de aceitunas", "ajo", "piel de limón y naranja", "tomillo", "aceite de oliva"],
      "Mezcla las aceitunas con ajo laminado, pieles de cítrico, tomillo y aceite. Deja marinar al menos un día en la nevera."),
    p("ap-hummus-cruidites", "Hummus con crudités",
      ["200 g de hummus", "zanahoria, apio y pimiento", "picos de pan"],
      "Sirve el hummus en un bol en el centro. Acompaña con bastones de verdura cruda y picos para mojar."),
])

# ===========================================================================
# 8) ENSALADAS  (img 4 + img 7 — agrupadas por subcategoría, preparación redactada)
# ===========================================================================
seccion("ensaladas", "Ensaladas frescas", "eco",
    "Veintidós ensaladas organizadas por tipo: de verduras, de féculas, gourmet y de temporada.", [
    # --- de verduras ---
    p("en-griega", "Ensalada griega", ["2 tomates", "1 pepino", "1/2 cebolla roja", "100 g de feta",
       "aceitunas negras", "orégano", "aceite de oliva"],
      "Trocea el tomate, el pepino y la cebolla en trozos grandes. Añade el feta en dados y las aceitunas, y aliña con aceite y orégano. No lleva lechuga.", subcategoria="De verduras"),
    p("en-col", "Ensalada de col (coleslaw)", ["1/4 de col", "2 zanahorias", "3 cucharadas de mayonesa",
       "1 cucharada de vinagre", "1 cucharadita de mostaza", "sal"],
      "Corta la col y la zanahoria en juliana muy fina. Mezcla la mayonesa con el vinagre y la mostaza y alíñala. Deja reposar para que ablande.", subcategoria="De verduras"),
    p("en-tomate-cebolla", "Ensalada de tomate y cebolla", ["3 tomates", "1/2 cebolla dulce",
       "aceite de oliva", "vinagre", "sal", "orégano"],
      "Corta los tomates en rodajas y la cebolla en pluma. Aliña con aceite, vinagre y sal y espolvorea orégano.", subcategoria="De verduras"),
    p("en-pepino-yogur", "Ensalada de pepino y yogur", ["2 pepinos", "150 g de yogur",
       "ajo", "menta", "aceite de oliva", "sal"],
      "Corta el pepino en rodajas finas. Mézclalo con el yogur, el ajo machacado, la menta y la sal. Sirve muy frío.", subcategoria="De verduras"),
    p("en-remolacha", "Ensalada de remolacha", ["2 remolachas cocidas", "1/2 cebolla roja",
       "queso de cabra", "nueces", "aceite y vinagre"],
      "Corta la remolacha en dados y mézclala con la cebolla. Reparte queso de cabra y nueces y aliña.", subcategoria="De verduras"),
    p("en-cesar", "Ensalada César", ["1 lechuga romana", "1 pechuga de pollo", "picatostes",
       "parmesano", "salsa césar", "anchoas opcional"],
      "Marca el pollo a la plancha y córtalo en tiras. Mezcla la lechuga con la salsa césar, añade el pollo, los picatostes y el parmesano en lascas.", subcategoria="De verduras"),
    # --- de féculas ---
    p("en-patata", "Ensalada de patata", ["500 g de patatas", "2 huevos duros", "1/2 cebolla",
       "pepinillos", "mayonesa", "perejil"],
      "Cuece las patatas y córtalas en dados. Mézclalas con el huevo, la cebolla y los pepinillos picados y liga con mayonesa.", subcategoria="De féculas"),
    p("en-pasta", "Ensalada de pasta", ["200 g de pasta corta", "tomates cherry", "mozzarella",
       "aceitunas", "albahaca", "aceite de oliva"],
      "Cuece la pasta al dente y enfríala. Mézclala con los cherry, la mozzarella y las aceitunas y aliña con aceite y albahaca.", subcategoria="De féculas"),
    p("en-arroz", "Ensalada de arroz", ["200 g de arroz", "1 lata de atún", "maíz", "pimiento",
       "huevo duro", "aceitunas", "aceite y vinagre"],
      "Cuece el arroz y enfríalo. Mézclalo con el atún, el maíz, el pimiento, el huevo y las aceitunas y aliña.", subcategoria="De féculas"),
    p("en-lentejas", "Ensalada de lentejas", ["250 g de lentejas cocidas", "1 tomate", "1/2 cebolla",
       "1 pimiento", "comino", "aceite y vinagre"],
      "Escurre las lentejas y mézclalas con el tomate, la cebolla y el pimiento picados. Aliña con aceite, vinagre y una pizca de comino.", subcategoria="De féculas"),
    p("en-quinoa", "Ensalada de quinoa", ["150 g de quinoa", "pepino", "tomate", "aguacate",
       "lima", "cilantro", "aceite de oliva"],
      "Cuece la quinoa y déjala enfriar. Mézclala con el pepino, el tomate y el aguacate en dados y aliña con lima, cilantro y aceite.", subcategoria="De féculas"),
    p("en-garbanzos", "Ensalada de garbanzos", ["250 g de garbanzos cocidos", "tomate", "pepino",
       "cebolla", "perejil", "comino", "aceite y limón"],
      "Mezcla los garbanzos con el tomate, el pepino y la cebolla picados. Aliña con aceite, limón, perejil y comino.", subcategoria="De féculas"),
    # --- gourmet ---
    p("en-salmon-aguacate", "Ensalada de salmón ahumado y aguacate", ["mezcla de hojas verdes",
       "100 g de salmón ahumado", "1 aguacate", "tomates cherry", "eneldo", "aceite y limón"],
      "Dispón las hojas en el plato y reparte el salmón, el aguacate laminado y los cherry. Aliña con aceite, limón y eneldo.", subcategoria="Gourmet"),
    p("en-cabra-nueces", "Ensalada de queso de cabra y nueces", ["hojas verdes", "1 rulo de cabra",
       "nueces", "miel", "vinagre balsámico", "aceite de oliva"],
      "Gratina rodajas de queso de cabra y colócalas sobre las hojas. Reparte nueces y aliña con miel, balsámico y aceite.", subcategoria="Gourmet"),
    p("en-jamon-melon", "Ensalada de jamón y melón", ["rúcula", "1/4 de melón", "80 g de jamón serrano",
       "lascas de parmesano", "aceite de oliva"],
      "Coloca la rúcula con el melón en dados y el jamón. Termina con lascas de parmesano y un hilo de aceite.", subcategoria="Gourmet"),
    p("en-pollo-mango", "Ensalada de pollo y mango", ["hojas verdes", "1 pechuga de pollo", "1 mango",
       "aguacate", "anacardos", "vinagreta de lima"],
      "Marca el pollo y córtalo en tiras. Móntalo sobre las hojas con el mango y el aguacate en dados y los anacardos, y aliña con vinagreta de lima.", subcategoria="Gourmet"),
    p("en-tofu-sesamo", "Ensalada de tofu y sésamo", ["200 g de tofu firme", "col lombarda",
       "zanahoria", "edamame", "salsa de soja", "aceite de sésamo", "sésamo"],
      "Dora el tofu en dados. Mézclalo con la col y la zanahoria en juliana y el edamame, y aliña con soja, aceite de sésamo y semillas.", subcategoria="Gourmet"),
    # --- de temporada ---
    p("en-verano", "Ensalada de verano (sandía y feta)", ["300 g de sandía", "100 g de feta",
       "menta", "aceitunas", "aceite de oliva", "limón"],
      "Corta la sandía en dados y mézclala con el feta y las aceitunas. Aliña con aceite, limón y menta. Dulce y salada.", subcategoria="De temporada"),
    p("en-otono", "Ensalada de otoño (calabaza asada)", ["300 g de calabaza", "espinacas baby",
       "nueces", "queso de cabra", "semillas", "vinagreta de miel"],
      "Asa la calabaza en dados hasta dorar. Móntala templada sobre las espinacas con nueces, queso y semillas y aliña con vinagreta de miel.", subcategoria="De temporada"),
    p("en-invierno", "Ensalada de invierno (naranja e hinojo)", ["2 naranjas", "1 bulbo de hinojo",
       "aceitunas negras", "granada", "aceite de oliva", "sal"],
      "Pela las naranjas a lo vivo y lamina el hinojo muy fino. Mézclalos con las aceitunas y la granada y aliña con aceite y sal.", subcategoria="De temporada"),
    p("en-primavera", "Ensalada de primavera (espárragos y guisantes)", ["1 manojo de espárragos verdes",
       "100 g de guisantes", "rúcula", "huevo poché", "parmesano", "aceite y limón"],
      "Saltea los espárragos y los guisantes y déjalos templar. Móntalos sobre la rúcula con un huevo poché y parmesano, y aliña con aceite y limón.", subcategoria="De temporada"),
    p("en-frutas", "Ensalada de frutas", ["1 manzana", "1 plátano", "1 naranja", "fresas", "uvas",
       "el zumo de 1 naranja", "menta"],
      "Trocea toda la fruta en tamaño similar. Mézclala con el zumo de naranja para que no se oxide y reparte unas hojas de menta.", subcategoria="De temporada"),
])

# ===========================================================================
# 9) POSTRES  (selección curada de las infografías rumanas de dulces)
# Recetas clásicas y fiables; imagen = ilustración propia generada (etiquetada).
# ===========================================================================
seccion("postres", "Postres", "icecream",
    "Doce postres clásicos, del tiramisú al coulant, con receta paso a paso.", [
    p("po-tiramisu", "Tiramisú",
      ["250 g de queso mascarpone", "3 huevos", "80 g de azúcar",
       "200 ml de café fuerte frío", "1 paquete de bizcochos de soletilla", "cacao en polvo para espolvorear"],
      "Separa las claras de las yemas. Bate las yemas con el azúcar hasta que blanqueen e incorpora el mascarpone hasta tener una crema lisa. Monta las claras a punto de nieve e intégralas con movimientos suaves. Moja brevemente los bizcochos en el café y forma una capa en una fuente; cubre con crema y repite. Termina con cacao espolvoreado y enfría al menos 4 horas.",
      image="img/secciones/po-tiramisu.jpg", ilustracion=True),
    p("po-coulant-chocolate", "Coulant de chocolate",
      ["120 g de chocolate negro", "100 g de mantequilla", "2 huevos", "60 g de azúcar",
       "40 g de harina", "una pizca de sal", "mantequilla y cacao para los moldes"],
      "Funde el chocolate con la mantequilla y deja templar. Bate los huevos con el azúcar y añade el chocolate, la harina tamizada y la sal. Reparte en moldes individuales engrasados y enfría 30 minutos. Hornea a 200 °C unos 9-10 minutos: el borde debe quedar cuajado y el centro líquido. Desmolda con cuidado y sirve enseguida.",
      image="img/secciones/po-coulant-chocolate.jpg", ilustracion=True),
    p("po-cheesecake", "Cheesecake sin horno",
      ["200 g de galletas tipo digestive", "90 g de mantequilla", "400 g de queso crema",
       "200 ml de nata para montar", "80 g de azúcar", "1 cucharadita de extracto de vainilla", "frutos rojos para cubrir"],
      "Tritura las galletas y mézclalas con la mantequilla fundida; presiona en la base de un molde y enfría. Bate el queso con el azúcar y la vainilla, monta la nata aparte e intégrala con suavidad. Vierte sobre la base, alisa y refrigera al menos 4 horas. Cubre con frutos rojos antes de servir.",
      image="img/secciones/po-cheesecake.jpg", ilustracion=True),
    p("po-panna-cotta", "Panna cotta de vainilla",
      ["500 ml de nata para montar", "80 g de azúcar", "1 vaina de vainilla o 1 cucharadita de extracto",
       "3 hojas de gelatina", "frutos rojos para el coulis"],
      "Hidrata la gelatina en agua fría. Calienta la nata con el azúcar y la vainilla sin que llegue a hervir, retira del fuego y disuelve la gelatina escurrida. Reparte en vasos y enfría al menos 4 horas hasta que cuaje. Tritura unos frutos rojos con un poco de azúcar y cubre la panna cotta antes de servir.",
      image="img/secciones/po-panna-cotta.jpg", ilustracion=True),
    p("po-mousse-chocolate", "Mousse de chocolate",
      ["150 g de chocolate negro", "3 huevos", "30 g de azúcar", "una pizca de sal"],
      "Funde el chocolate y déjalo templar. Separa las claras de las yemas e incorpora las yemas al chocolate. Monta las claras con la sal y, cuando estén espumosas, añade el azúcar hasta un merengue firme. Integra el merengue en el chocolate con movimientos envolventes para no bajarlo. Reparte en vasos y enfría al menos 3 horas.",
      image="img/secciones/po-mousse-chocolate.jpg", ilustracion=True),
    p("po-tarta-limon", "Tarta de crema de limón",
      ["1 base de masa quebrada", "4 huevos", "150 g de azúcar",
       "el zumo de 3 limones y la ralladura de 1", "100 g de mantequilla", "1 cucharada de maicena"],
      "Hornea la base de masa quebrada en blanco a 180 °C unos 15 minutos. Mezcla los huevos con el azúcar, el zumo y la ralladura de limón y la maicena, y cocina a fuego suave removiendo hasta que espese. Retira, incorpora la mantequilla en trozos y rellena la base. Enfría hasta que cuaje y sirve fría.",
      image="img/secciones/po-tarta-limon.jpg", ilustracion=True),
    p("po-crepes", "Crepes rellenas",
      ["2 huevos", "250 ml de leche", "120 g de harina", "1 cucharada de azúcar",
       "una pizca de sal", "mantequilla para la sartén", "crema y frutos rojos para rellenar"],
      "Bate los huevos con la leche, la harina, el azúcar y la sal hasta una masa fina y sin grumos; deja reposar 20 minutos. Engrasa una sartén y vierte un cucharón extendiéndolo fino; cuaja un minuto por cada lado. Rellena con crema y frutos rojos, dobla y espolvorea azúcar.",
      image="img/secciones/po-crepes.jpg", ilustracion=True),
    p("po-budin-chia", "Budín de chía con frutos rojos",
      ["3 cucharadas de semillas de chía", "250 ml de leche o bebida vegetal", "1 cucharada de miel o sirope",
       "1/2 cucharadita de vainilla", "frutos rojos y yogur para montar"],
      "Mezcla la chía con la leche, la miel y la vainilla y remueve bien para que no se apelmace. Deja reposar en la nevera al menos 4 horas (mejor toda la noche), removiendo una vez a media espera. Monta en vasos alternando con yogur y frutos rojos.",
      image="img/secciones/po-budin-chia.jpg", ilustracion=True),
    p("po-bundt-limon", "Bizcocho bundt de limón",
      ["3 huevos", "200 g de azúcar", "200 g de harina", "120 ml de aceite suave",
       "120 ml de yogur natural", "la ralladura de 2 limones y su zumo", "1 sobre de levadura química",
       "azúcar glas y zumo de limón para el glaseado"],
      "Bate los huevos con el azúcar hasta que doblen su volumen. Añade el aceite, el yogur, la ralladura y el zumo de limón. Incorpora la harina con la levadura tamizadas. Vierte en un molde de bundt engrasado y hornea a 175 °C unos 40 minutos hasta que al pinchar salga limpio. Desmolda, deja enfriar y cubre con un glaseado de azúcar glas y limón.",
      image="img/secciones/po-bundt-limon.jpg", ilustracion=True),
    p("po-pavlova", "Pavlova de frutos rojos",
      ["4 claras de huevo", "200 g de azúcar", "1 cucharadita de maicena", "1 cucharadita de vinagre",
       "250 ml de nata para montar", "frutos rojos para cubrir"],
      "Monta las claras y añade el azúcar en varias veces hasta un merengue firme y brillante; incorpora la maicena y el vinagre. Forma un disco sobre papel de hornear y hornea a 120 °C unos 70 minutos; deja enfriar dentro del horno apagado. Cubre con nata montada y frutos rojos justo antes de servir.",
      image="img/secciones/po-pavlova.jpg", ilustracion=True),
    p("po-sorbete-limon", "Sorbete de limón",
      ["250 ml de zumo de limón", "150 g de azúcar", "250 ml de agua",
       "la ralladura de 1 limón", "1 clara de huevo (opcional)"],
      "Calienta el agua con el azúcar hasta disolverlo y deja enfriar este almíbar. Mézclalo con el zumo y la ralladura de limón. Congela en un recipiente removiendo con un tenedor cada 30-40 minutos para romper los cristales; para una textura más suave, integra la clara montada a media congelación. Está listo cuando quede firme pero cremoso.",
      image="img/secciones/po-sorbete-limon.jpg", ilustracion=True),
    p("po-natillas", "Natillas caseras",
      ["500 ml de leche", "4 yemas de huevo", "100 g de azúcar", "1 cucharada de maicena",
       "1 rama de canela", "la piel de 1/2 limón", "canela en polvo y galletas para servir"],
      "Infusiona la leche con la canela en rama y la piel de limón y retírala antes de que hierva. Bate las yemas con el azúcar y la maicena, añade la leche templada y colada y cocina a fuego suave removiendo hasta que espese sin hervir. Reparte en cuencos, espolvorea canela y sirve con una galleta.",
      image="img/secciones/po-natillas.jpg", ilustracion=True),
])

# ===========================================================================
# 10) DIPS Y UNTABLES  (img 6 — dips mediterráneos, traían ingredientes)
# ===========================================================================
seccion("dips", "Dips y untables", "tapas",
    "Ocho dips clásicos para mojar pan, crudités y picoteo.", [
    p("dip-hummus", "Hummus",
      ["400 g de garbanzos cocidos", "2 cucharadas de tahini", "el zumo de 1 limón", "1 diente de ajo",
       "3 cucharadas de aceite de oliva virgen extra", "1/2 cucharadita de comino", "sal al gusto", "agua fría al gusto"],
      "Escurre los garbanzos reservando un poco del líquido. Tritúralos con el tahini, el zumo de limón, el ajo, el comino y la sal hasta una pasta. Añade el aceite y un poco de agua fría mientras bates hasta que quede cremoso. Sirve con un hilo de aceite y pimentón.",
      image="img/secciones/dip-hummus.jpg", ilustracion=True),
    p("dip-guacamole", "Guacamole",
      ["2 aguacates maduros", "1/2 cebolla pequeña picada", "1 tomate picado", "el zumo de 1 lima",
       "unas hojas de cilantro", "1 chile o guindilla (opcional)", "sal al gusto"],
      "Abre los aguacates y aplástalos con un tenedor dejando algo de textura. Mezcla con la cebolla, el tomate, el cilantro y el chile bien picados. Aliña con el zumo de lima y la sal. Sírvelo recién hecho para que no se oxide.",
      image="img/secciones/dip-guacamole.jpg", ilustracion=True),
    p("dip-tzatziki", "Tzatziki",
      ["250 g de yogur griego", "1/2 pepino", "1 diente de ajo", "1 cucharada de aceite de oliva",
       "1 cucharadita de vinagre o limón", "unas hojas de menta o eneldo", "sal al gusto"],
      "Ralla el pepino, sálalo y escúrrelo bien apretando para quitar el agua. Mézclalo con el yogur, el ajo rallado, el aceite y el vinagre. Añade la menta picada y la sal, y enfría al menos 1 hora antes de servir.",
      image="img/secciones/dip-tzatziki.jpg", ilustracion=True),
    p("dip-baba-ganoush", "Baba ganoush",
      ["2 berenjenas", "2 cucharadas de tahini", "el zumo de 1 limón", "1 diente de ajo",
       "2 cucharadas de aceite de oliva", "sal al gusto", "perejil para servir"],
      "Asa las berenjenas enteras al horno a 200 °C unos 40 minutos hasta que estén muy blandas. Deja templar, retira la piel y escurre la pulpa. Tritúrala o cháfala con el tahini, el ajo, el zumo de limón y la sal. Sirve con aceite y perejil por encima.",
      image="img/secciones/dip-baba-ganoush.jpg", ilustracion=True),
    p("dip-pico-gallo", "Pico de gallo",
      ["3 tomates maduros", "1/2 cebolla", "1 chile jalapeño (opcional)", "el zumo de 1 lima",
       "cilantro picado", "sal al gusto"],
      "Pica los tomates, la cebolla y el chile en dados muy pequeños. Mézclalos con el cilantro, el zumo de lima y la sal. Deja reposar 10 minutos para que se integren los sabores antes de servir.",
      image="img/secciones/dip-pico-gallo.jpg", ilustracion=True),
    p("dip-alioli", "Alioli",
      ["1 huevo", "1 diente de ajo", "200 ml de aceite de oliva suave", "unas gotas de limón", "sal al gusto"],
      "Pon el huevo, el ajo, el limón y la sal en el vaso de la batidora. Cubre con el aceite y bate con la batidora pegada al fondo sin moverla hasta que emulsione. Sube despacio para integrar todo el aceite hasta lograr una salsa firme. Consérvala en frío.",
      image="img/secciones/dip-alioli.jpg", ilustracion=True),
    p("dip-muhammara", "Muhammara",
      ["2 pimientos rojos asados", "60 g de nueces", "1 rebanada de pan tostado",
       "1 cucharada de melaza de granada (o un poco de vinagre)", "1 cucharadita de comino",
       "2 cucharadas de aceite de oliva", "sal al gusto"],
      "Tritura los pimientos asados y pelados con las nueces, el pan, el comino y la melaza de granada. Añade el aceite en hilo hasta una pasta espesa y rectifica de sal. Sirve con un poco más de aceite y nueces picadas.",
      image="img/secciones/dip-muhammara.jpg", ilustracion=True),
    p("dip-tapenade", "Tapenade de aceitunas",
      ["200 g de aceitunas negras deshuesadas", "2 cucharadas de alcaparras", "2 filetes de anchoa",
       "1 diente de ajo", "3 cucharadas de aceite de oliva", "unas gotas de limón"],
      "Pica las aceitunas, las alcaparras, las anchoas y el ajo. Tritúralos con el aceite y el limón hasta una pasta rústica, no demasiado fina. Úsala sobre pan tostado o como acompañamiento.",
      image="img/secciones/dip-tapenade.jpg", ilustracion=True),
])

# ===========================================================================
# 11) CREMAS FRÍAS  (img 40 — cremas frías del Mediterráneo; purés fríos)
# ===========================================================================
seccion("cremas-frias", "Cremas frías", "soup_kitchen",
    "Diez purés fríos cremosos para el verano, más allá del gazpacho.", [
    p("cf-vichyssoise", "Vichyssoise",
      ["3 puerros (parte blanca)", "2 patatas", "1 cebolla", "750 ml de caldo de verduras",
       "100 ml de nata", "30 g de mantequilla", "sal y pimienta", "cebollino para servir"],
      "Rehoga el puerro y la cebolla picados en la mantequilla sin que tomen color. Añade la patata en trozos y el caldo, y cuece 20 minutos hasta que esté tierna. Tritura muy fino, incorpora la nata y salpimienta. Enfría al menos 3 horas y sirve con cebollino picado.",
      image="img/secciones/cf-vichyssoise.jpg", ilustracion=True),
    p("cf-remolacha", "Crema fría de remolacha",
      ["3 remolachas cocidas", "1 yogur natural", "1 diente de ajo pequeño", "el zumo de 1/2 limón",
       "200 ml de agua fría", "2 cucharadas de aceite de oliva", "sal y pimienta", "eneldo para servir"],
      "Tritura las remolachas con el yogur, el ajo, el limón y el agua hasta una crema fina. Emulsiona con el aceite y salpimienta. Enfría bien y sirve con un poco de yogur y eneldo por encima.",
      image="img/secciones/cf-remolacha.jpg", ilustracion=True),
    p("cf-aguacate", "Crema fría de aguacate",
      ["2 aguacates maduros", "1 pepino", "el zumo de 1 lima", "200 ml de caldo o agua fría",
       "1 yogur natural", "unas hojas de cilantro", "sal y pimienta"],
      "Tritura los aguacates con el pepino pelado, el yogur, la lima y el caldo hasta que quede sedoso. Añade el cilantro y salpimienta. Sirve muy frío; si espesa, aclara con un poco más de agua.",
      image="img/secciones/cf-aguacate.jpg", ilustracion=True),
    p("cf-calabacin", "Crema fría de calabacín",
      ["3 calabacines", "1 cebolla", "50 g de queso crema", "600 ml de caldo de verduras",
       "2 cucharadas de aceite de oliva", "sal y pimienta"],
      "Rehoga la cebolla y el calabacín en trozos con el aceite unos minutos. Añade el caldo y cuece 15 minutos. Tritura con el queso hasta una crema fina, salpimienta y enfría. Sirve frío con un hilo de aceite.",
      image="img/secciones/cf-calabacin.jpg", ilustracion=True),
    p("cf-zanahoria", "Crema fría de zanahoria y naranja",
      ["500 g de zanahorias", "1 cebolla", "el zumo de 2 naranjas", "600 ml de caldo de verduras",
       "2 cucharadas de aceite de oliva", "una pizca de jengibre", "sal y pimienta"],
      "Rehoga la cebolla y la zanahoria en rodajas con el aceite. Añade el caldo y el jengibre y cuece 20 minutos. Tritura con el zumo de naranja hasta una crema fina, salpimienta y enfría. Sirve fría.",
      image="img/secciones/cf-zanahoria.jpg", ilustracion=True),
    p("cf-guisantes-menta", "Crema fría de guisantes y menta",
      ["400 g de guisantes", "1 cebolleta", "500 ml de caldo de verduras", "unas hojas de menta",
       "2 cucharadas de aceite de oliva", "sal y pimienta", "yogur para servir"],
      "Rehoga la cebolleta, añade los guisantes y el caldo y cuece 10 minutos. Tritura con la menta hasta una crema fina y cuela si quieres. Salpimienta, enfría y sirve con una cucharada de yogur.",
      image="img/secciones/cf-guisantes-menta.jpg", ilustracion=True),
    p("cf-melon-jamon", "Crema fría de melón con jamón",
      ["1/2 melón maduro", "100 ml de agua fría o caldo", "1 cucharada de aceite de oliva",
       "una pizca de sal", "menta", "50 g de jamón serrano para servir"],
      "Tritura el melón con el agua, el aceite y la sal hasta una crema fina. Enfría bien. Sirve con unas virutas de jamón serrano y unas hojas de menta.",
      image="img/secciones/cf-melon-jamon.jpg", ilustracion=True),
    p("cf-pepino-yogur", "Crema fría de pepino y yogur",
      ["2 pepinos", "250 g de yogur griego", "1 diente de ajo pequeño", "1 cucharada de aceite de oliva",
       "el zumo de 1/2 limón", "eneldo", "sal y pimienta"],
      "Tritura los pepinos pelados con el yogur, el ajo, el limón y el aceite hasta una crema. Añade eneldo y salpimienta. Enfría bien y sirve; es muy refrescante en verano.",
      image="img/secciones/cf-pepino-yogur.jpg", ilustracion=True),
    p("cf-calabaza", "Crema fría de calabaza",
      ["500 g de calabaza", "1 cebolla", "1 zanahoria", "600 ml de caldo de verduras",
       "2 cucharadas de aceite de oliva", "una pizca de nuez moscada", "sal y pimienta"],
      "Rehoga la cebolla, la zanahoria y la calabaza en trozos. Añade el caldo y cuece 20 minutos hasta que estén tiernas. Tritura con la nuez moscada hasta una crema fina, salpimienta y enfría. Sirve fría con un hilo de aceite.",
      image="img/secciones/cf-calabaza.jpg", ilustracion=True),
    p("cf-esparragos", "Crema fría de espárragos",
      ["1 manojo de espárragos verdes", "1 puerro", "1 patata pequeña", "600 ml de caldo de verduras",
       "2 cucharadas de aceite de oliva", "sal y pimienta"],
      "Rehoga el puerro y la patata, añade los espárragos troceados (reserva las puntas) y el caldo, y cuece 15 minutos. Tritura muy fino y salpimienta. Saltea las puntas reservadas y úsalas para decorar. Sirve frío.",
      image="img/secciones/cf-esparragos.jpg", ilustracion=True),
])

# ===========================================================================
# 12) TORTILLAS Y HUEVOS  (img 59 — platos de huevo)
# ===========================================================================
seccion("huevos", "Tortillas y huevos", "egg",
    "Ocho clásicos del huevo para desayuno, comida o cena rápida.", [
    p("hv-tortilla-espanola", "Tortilla española",
      ["5 huevos", "4 patatas medianas", "1 cebolla (opcional)", "aceite de oliva para freír", "sal"],
      "Pela y corta las patatas en láminas finas (y la cebolla en juliana). Fríelas a fuego medio en abundante aceite hasta que estén tiernas, escúrrelas y sálalas. Bate los huevos, mézclalos con la patata y cuaja la tortilla en una sartén con un poco de aceite, dándole la vuelta con un plato. Déjala jugosa por dentro.",
      image="img/secciones/hv-tortilla-espanola.jpg", ilustracion=True),
    p("hv-tortilla-francesa", "Tortilla francesa",
      ["2 huevos", "1 cucharadita de aceite o mantequilla", "sal", "perejil o queso (opcional)"],
      "Bate los huevos con una pizca de sal. Calienta el aceite en una sartén pequeña, vierte el huevo y, cuando empiece a cuajar por los bordes, recógelo hacia el centro. Enróllala sobre sí misma y sirve jugosa. Añade queso o perejil al gusto.",
      image="img/secciones/hv-tortilla-francesa.jpg", ilustracion=True),
    p("hv-huevos-rotos", "Huevos rotos con patatas",
      ["3 patatas", "4 huevos", "aceite de oliva", "sal", "jamón o chorizo (opcional)"],
      "Corta las patatas en bastones y fríelas hasta que estén doradas y tiernas. Fríe los huevos en aceite caliente dejando la yema líquida. Coloca los huevos sobre las patatas, rómpelos y mezcla. Añade jamón o chorizo si quieres.",
      image="img/secciones/hv-huevos-rotos.jpg", ilustracion=True),
    p("hv-revuelto-setas", "Revuelto de setas",
      ["4 huevos", "200 g de setas variadas", "1 diente de ajo", "2 cucharadas de aceite de oliva", "perejil", "sal y pimienta"],
      "Saltea las setas troceadas con el ajo y un poco de aceite hasta que suelten el agua y se doren. Baja el fuego, añade los huevos batidos y remueve sin parar hasta que cuajen cremosos. Salpimienta y termina con perejil.",
      image="img/secciones/hv-revuelto-setas.jpg", ilustracion=True),
    p("hv-shakshuka", "Shakshuka",
      ["4 huevos", "400 g de tomate triturado", "1 cebolla", "1 pimiento rojo", "1 diente de ajo",
       "1 cucharadita de comino", "1 cucharadita de pimentón", "aceite de oliva", "sal", "perejil o cilantro"],
      "Rehoga la cebolla, el pimiento y el ajo. Añade el tomate, el comino y el pimentón y cuece 10 minutos hasta que espese. Haz huecos y casca los huevos dentro; tapa y cocina a fuego suave hasta que cuajen las claras y la yema quede líquida. Sirve con hierbas.",
      image="img/secciones/hv-shakshuka.jpg", ilustracion=True),
    p("hv-huevos-rellenos", "Huevos rellenos",
      ["6 huevos", "100 g de atún", "3 cucharadas de mayonesa", "1 cucharada de tomate frito", "sal"],
      "Cuece los huevos 10 minutos, enfría y pélalos. Pártelos por la mitad y saca las yemas. Mezcla las yemas con el atún, la mayonesa y el tomate hasta una pasta. Rellena las claras con la mezcla y decora con un poco más de mayonesa.",
      image="img/secciones/hv-huevos-rellenos.jpg", ilustracion=True),
    p("hv-huevos-benedictinos", "Huevos benedictinos",
      ["2 huevos", "2 muffins ingleses o rebanadas de pan", "2 lonchas de bacon o jamón", "1 cucharada de vinagre",
       "2 yemas, 100 g de mantequilla, zumo de limón y sal para la holandesa"],
      "Escalfa los huevos en agua con vinagre unos 3 minutos. Tuesta el pan y calienta el bacon. Prepara la holandesa batiendo las yemas al baño maría e incorporando la mantequilla fundida y el limón hasta que espese. Monta el pan con el bacon, el huevo escalfado y la salsa por encima.",
      image="img/secciones/hv-huevos-benedictinos.jpg", ilustracion=True),
    p("hv-tortilla-calabacin", "Tortilla de calabacín",
      ["4 huevos", "2 calabacines", "1 cebolla", "aceite de oliva", "sal"],
      "Pocha el calabacín en rodajas con la cebolla y un poco de aceite hasta que estén tiernos. Bate los huevos, mézclalos con la verdura escurrida y cuaja la tortilla por ambos lados en la sartén. Déjala jugosa.",
      image="img/secciones/hv-tortilla-calabacin.jpg", ilustracion=True),
])

# ===========================================================================
# 13) CLÁSICOS RUMANOS SALADOS  (recetas tradicionales documentadas)
# ===========================================================================
seccion("rumanos", "Clásicos rumanos salados", "ramen_dining",
    "Diez platos tradicionales de Rumanía, tal como se cocinan en casa.", [
    p("ro-sarmale", "Sarmale (rollitos de col rumanos)",
      ["1 col fermentada o blanca", "500 g de carne picada de cerdo", "100 g de arroz",
       "1 cebolla", "400 g de tomate triturado", "1 cucharadita de pimentón", "tomillo", "sal y pimienta",
       "lonchas de panceta ahumada (opcional)"],
      "Pocha la cebolla picada y mézclala con la carne, el arroz crudo, el pimentón, sal y pimienta. Separa las hojas de col, recorta el nervio y pon un poco de relleno en cada una; enróllalas metiendo los lados. Coloca los rollitos apretados en una olla sobre un lecho de col picada y panceta, cubre con el tomate, el tomillo y agua, y cuece tapado a fuego muy suave 2-3 horas (o al horno). Se sirven con polenta y nata agria.",
      image="img/secciones/ro-sarmale.jpg", ilustracion=True),
    p("ro-mamaliga", "Mămăligă con queso y nata",
      ["250 g de harina de maíz", "1 l de agua", "1 cucharadita de sal",
       "150 g de queso fresco rumano (telemea) o feta", "nata agria (smântână)", "mantequilla"],
      "Lleva el agua con sal a ebullición y añade la harina de maíz en lluvia removiendo sin parar con varillas para que no se formen grumos. Cuece a fuego medio 20-30 minutos removiendo a menudo hasta que se despegue de las paredes. Sirve la polenta caliente con el queso desmenuzado, una cucharada de nata agria y mantequilla.",
      image="img/secciones/ro-mamaliga.jpg", ilustracion=True),
    p("ro-mici", "Mici (mititei a la parrilla)",
      ["500 g de carne picada de ternera", "200 g de carne picada de cerdo", "3 dientes de ajo",
       "1 cucharadita de bicarbonato", "1 cucharadita de comino", "1 cucharadita de pimentón",
       "100 ml de caldo de carne", "sal y pimienta"],
      "Mezcla las dos carnes con el ajo machacado, el comino, el pimentón, el bicarbonato, sal y pimienta, e incorpora el caldo frío poco a poco hasta una masa pegajosa. Deja reposar tapada en la nevera unas horas (mejor toda la noche). Forma rollitos del tamaño de un dedo grueso y ásalos a la parrilla bien caliente, girándolos, hasta que estén dorados por fuera y jugosos. Sirve con mostaza y pan.",
      image="img/secciones/ro-mici.jpg", ilustracion=True),
    p("ro-tochitura", "Tochitură moldava",
      ["600 g de carne de cerdo en tacos", "150 g de panceta ahumada", "150 g de salchicha rumana",
       "1 cebolla", "3 dientes de ajo", "2 cucharadas de tomate concentrado", "1 hoja de laurel",
       "manteca o aceite", "sal y pimienta", "huevos fritos y polenta para servir"],
      "Dora la panceta y la carne de cerdo en una cazuela con un poco de manteca. Añade la cebolla picada y el ajo y rehoga. Incorpora el tomate, el laurel y agua que cubra, salpimienta y guisa a fuego lento 1 hora hasta que la carne esté tierna y la salsa concentrada; añade la salchicha en rodajas al final. Sirve con polenta y un huevo frito encima.",
      image="img/secciones/ro-tochitura.jpg", ilustracion=True),
    p("ro-ardei-umpluti", "Ardei umpluți (pimientos rellenos)",
      ["6 pimientos para rellenar", "500 g de carne picada mixta", "80 g de arroz", "1 cebolla",
       "400 g de tomate triturado", "1 zanahoria", "eneldo y perejil", "sal y pimienta", "nata agria"],
      "Pocha la cebolla y mézclala con la carne, el arroz, las hierbas, sal y pimienta. Vacía los pimientos de semillas y rellénalos sin apretar (el arroz crece). Colócalos de pie en una olla, cúbrelos con el tomate y la zanahoria rallada con agua, y cuece tapado a fuego suave 45-60 minutos. Sirve con una cucharada de nata agria.",
      image="img/secciones/ro-ardei-umpluti.jpg", ilustracion=True),
    p("ro-ciorba-perisoare", "Ciorbă de perișoare (sopa agria de albóndigas)",
      ["300 g de carne picada", "2 cucharadas de arroz", "1 cebolla", "2 zanahorias", "1 chirivía",
       "1 pimiento", "100 ml de borș o zumo de limón", "perejil y levístico (apio de monte)", "sal"],
      "Cuece en agua con sal la cebolla, las zanahorias, la chirivía y el pimiento en dados. Mezcla la carne con el arroz y un poco de cebolla, forma albóndigas pequeñas y échalas a la sopa hirviendo; cuece 20 minutos. Agria la sopa con el borș (o limón) y hierve un par de minutos más. Termina con abundante perejil y levístico picados.",
      image="img/secciones/ro-ciorba-perisoare.jpg", ilustracion=True),
    p("ro-salata-boeuf", "Salată de boeuf (ensalada rusa rumana)",
      ["300 g de ternera o pollo cocido", "3 patatas", "2 zanahorias", "100 g de guisantes",
       "100 g de pepinillos en vinagre", "200 g de mayonesa", "1 cucharada de mostaza", "sal"],
      "Cuece la carne y, por separado, las patatas y las zanahorias; déjalo enfriar. Corta todo en dados muy pequeños junto con los pepinillos y mézclalo con los guisantes, la mayonesa, la mostaza y sal. Refrigera al menos 2 horas y sirve bien fría, alisada y decorada con pepinillo o pimiento.",
      image="img/secciones/ro-salata-boeuf.jpg", ilustracion=True),
    p("ro-chiftele", "Chiftele (albóndigas fritas rumanas)",
      ["500 g de carne picada de cerdo", "1 patata cruda rallada", "1 cebolla", "1 huevo",
       "2 dientes de ajo", "eneldo", "harina para rebozar", "aceite para freír", "sal y pimienta"],
      "Mezcla la carne con la patata rallada y escurrida, la cebolla rallada, el ajo, el huevo, el eneldo, sal y pimienta. Forma bolas algo aplanadas, pásalas por harina y fríelas en aceite caliente hasta que estén doradas por ambos lados y cocidas por dentro. Escúrrelas sobre papel y sírvelas calientes o frías.",
      image="img/secciones/ro-chiftele.jpg", ilustracion=True),
    p("ro-ostropel-pui", "Ostropel de pollo",
      ["1 pollo troceado", "6 dientes de ajo", "400 g de tomate triturado", "1 cucharada de harina",
       "2 cucharadas de aceite", "perejil", "sal y pimienta"],
      "Dora los trozos de pollo en aceite y resérvalos. En la misma cazuela rehoga la harina un minuto, añade el tomate, el ajo machacado, sal y pimienta y un poco de agua. Devuelve el pollo, tapa y guisa a fuego lento 30-40 minutos hasta que esté tierno y la salsa espesa y muy ajada. Espolvorea perejil y sirve con polenta o pan.",
      image="img/secciones/ro-ostropel-pui.jpg", ilustracion=True),
    p("ro-cartofi-taranesti", "Cartofi țărănești (patatas a la campesina)",
      ["800 g de patatas", "200 g de costilla o panceta ahumada", "2 cebollas", "2 dientes de ajo",
       "1 pimiento rojo", "1 cucharadita de pimentón", "tomillo", "aceite", "sal y pimienta"],
      "Dora la costilla en dados y resérvala. Rehoga la cebolla, el ajo y el pimiento en la grasa. Añade las patatas en gajos, el pimentón y el tomillo, salpimienta y agrega un poco de agua. Devuelve la carne, tapa y cocina a fuego medio (o al horno) hasta que las patatas estén tiernas y melosas.",
      image="img/secciones/ro-cartofi-taranesti.jpg", ilustracion=True),
])

# ===========================================================================
# 14) CROQUETAS  (clásico español; todas sobre base de bechamel)
# ===========================================================================
seccion("croquetas", "Croquetas caseras", "lunch_dining",
    "Ocho croquetas cremosas por dentro y crujientes por fuera, sobre una buena bechamel.", [
    p("cq-jamon", "Croquetas de jamón",
      ["100 g de jamón serrano picado", "60 g de mantequilla", "70 g de harina", "600 ml de leche",
       "nuez moscada", "sal y pimienta", "2 huevos y pan rallado para empanar", "aceite para freír"],
      "Funde la mantequilla, sofríe el jamón un minuto y añade la harina; cuécela 2 minutos. Vierte la leche caliente poco a poco sin dejar de remover hasta una bechamel espesa y lisa; sazona con nuez moscada, sal y pimienta. Extiéndela en una fuente, cúbrela a piel y enfría varias horas. Forma las croquetas, pásalas por huevo y pan rallado y fríelas en aceite caliente hasta dorarlas.",
      image="img/secciones/cq-jamon.jpg", ilustracion=True),
    p("cq-pollo", "Croquetas de pollo",
      ["250 g de pollo cocido o asado desmenuzado", "60 g de mantequilla", "70 g de harina", "600 ml de leche",
       "1/2 cebolla", "nuez moscada", "sal y pimienta", "2 huevos y pan rallado", "aceite para freír"],
      "Pocha la cebolla muy picada en la mantequilla, añade el pollo y la harina y rehoga 2 minutos. Incorpora la leche caliente en varias veces removiendo hasta una bechamel espesa; salpimienta con nuez moscada. Enfría la masa bien tapada, forma las croquetas, empánalas con huevo y pan rallado y fríelas doradas.",
      image="img/secciones/cq-pollo.jpg", ilustracion=True),
    p("cq-bacalao", "Croquetas de bacalao",
      ["250 g de bacalao desalado y desmigado", "60 g de mantequilla", "70 g de harina", "600 ml de leche",
       "1 diente de ajo", "perejil", "nuez moscada", "sal", "2 huevos y pan rallado", "aceite para freír"],
      "Saltea el ajo picado y el bacalao en la mantequilla, añade la harina y cuécela 2 minutos. Vierte la leche caliente poco a poco hasta una bechamel espesa; ajusta de sal (ojo, el bacalao ya sala), nuez moscada y perejil. Enfría tapada, forma las croquetas, rebózalas en huevo y pan rallado y fríelas doradas.",
      image="img/secciones/cq-bacalao.jpg", ilustracion=True),
    p("cq-espinacas", "Croquetas de espinacas",
      ["250 g de espinacas cocidas y escurridas", "60 g de mantequilla", "70 g de harina", "550 ml de leche",
       "1 diente de ajo", "30 g de piñones (opcional)", "nuez moscada", "sal y pimienta",
       "2 huevos y pan rallado", "aceite para freír"],
      "Saltea el ajo y las espinacas bien escurridas y picadas con los piñones. Añade la harina, rehoga y vierte la leche caliente poco a poco hasta una bechamel espesa; salpimienta con nuez moscada. Enfría la masa, forma las croquetas, empánalas y fríelas hasta dorarlas.",
      image="img/secciones/cq-espinacas.jpg", ilustracion=True),
    p("cq-queso", "Croquetas de queso",
      ["120 g de queso curado o azul rallado", "60 g de mantequilla", "70 g de harina", "600 ml de leche",
       "nuez moscada", "sal y pimienta", "2 huevos y pan rallado", "aceite para freír"],
      "Prepara una bechamel espesa: funde la mantequilla, cuece la harina 2 minutos y añade la leche caliente removiendo. Fuera del fuego incorpora el queso hasta que se funda y sazona con nuez moscada, sal y pimienta. Enfría bien tapada, forma las croquetas, empánalas con huevo y pan rallado y fríelas doradas.",
      image="img/secciones/cq-queso.jpg", ilustracion=True),
    p("cq-setas", "Croquetas de setas",
      ["250 g de setas variadas", "60 g de mantequilla", "70 g de harina", "600 ml de leche",
       "1/2 cebolla", "nuez moscada", "sal y pimienta", "2 huevos y pan rallado", "aceite para freír"],
      "Saltea la cebolla y las setas muy picadas hasta que pierdan el agua y se doren. Añade la harina, rehoga 2 minutos y vierte la leche caliente poco a poco hasta una bechamel espesa; salpimienta con nuez moscada. Enfría la masa, forma las croquetas, empánalas y fríelas crujientes.",
      image="img/secciones/cq-setas.jpg", ilustracion=True),
    p("cq-cocido", "Croquetas de cocido",
      ["250 g de carne del cocido o puchero desmenuzada", "60 g de mantequilla", "70 g de harina", "600 ml de leche",
       "1/2 cebolla", "nuez moscada", "sal y pimienta", "2 huevos y pan rallado", "aceite para freír"],
      "Aprovecha las carnes del cocido picadas finas. Pocha la cebolla en la mantequilla, añade la carne y la harina y rehoga. Incorpora la leche caliente poco a poco hasta una bechamel espesa; salpimienta con nuez moscada. Enfría tapada, forma las croquetas, empánalas con huevo y pan rallado y fríelas doradas.",
      image="img/secciones/cq-cocido.jpg", ilustracion=True),
    p("cq-gambas", "Croquetas de gambas",
      ["250 g de gambas peladas", "60 g de mantequilla", "70 g de harina", "550 ml de leche",
       "100 ml del caldo de las cáscaras", "1/2 cebolla", "nuez moscada", "sal", "2 huevos y pan rallado",
       "aceite para freír"],
      "Hierve las cáscaras de las gambas unos minutos para un caldo corto. Pocha la cebolla, saltea las gambas troceadas, añade la harina y rehoga. Vierte la leche y el caldo calientes poco a poco hasta una bechamel espesa; sazona con nuez moscada y sal. Enfría la masa, forma las croquetas, empánalas y fríelas doradas.",
      image="img/secciones/cq-gambas.jpg", ilustracion=True),
])

# ===========================================================================
# 15) LIMONADAS Y AGUAS FRESCAS  (bebidas refrescantes sin alcohol)
# ===========================================================================
seccion("limonadas", "Limonadas y aguas frescas", "local_bar",
    "Nueve bebidas refrescantes caseras para el verano, sin alcohol.", [
    p("lm-clasica", "Limonada clásica",
      ["4 limones", "1 l de agua", "4-5 cucharadas de azúcar", "hielo"],
      "Exprime los limones y mezcla el zumo con el agua. Disuelve el azúcar removiendo y prueba para ajustar el dulzor. Sirve bien fría con hielo y unas rodajas de limón.",
      image="img/secciones/lm-clasica.jpg", ilustracion=True),
    p("lm-fresa", "Limonada de fresa",
      ["200 g de fresas", "3 limones", "1 l de agua", "4 cucharadas de azúcar", "hielo"],
      "Tritura las fresas con un poco de agua y cuela si quieres una textura limpia. Mézclalas con el zumo de limón, el resto del agua y el azúcar al gusto. Sirve muy fría con hielo.",
      image="img/secciones/lm-fresa.jpg", ilustracion=True),
    p("lm-menta-pepino", "Limonada de menta y pepino",
      ["1/2 pepino", "3 limones", "1 l de agua", "un puñado de hojas de menta", "3 cucharadas de azúcar o miel", "hielo"],
      "Tritura el pepino con la menta y un poco de agua y cuela. Mezcla con el zumo de limón, el resto del agua y el endulzante. Sirve con hielo, rodajas de pepino y hojas de menta.",
      image="img/secciones/lm-menta-pepino.jpg", ilustracion=True),
    p("lm-naranjada", "Naranjada casera",
      ["4 naranjas", "1 limón", "700 ml de agua", "2-3 cucharadas de azúcar", "hielo"],
      "Exprime las naranjas y el limón. Mezcla los zumos con el agua y endulza al gusto (las naranjas ya aportan dulzor). Sirve muy fría con hielo y rodajas de naranja.",
      image="img/secciones/lm-naranjada.jpg", ilustracion=True),
    p("lm-agua-sandia", "Agua de sandía",
      ["600 g de sandía sin pepitas", "el zumo de 1 lima", "500 ml de agua", "azúcar al gusto (opcional)", "hielo"],
      "Tritura la sandía y cuela el zumo. Mézclalo con el agua y la lima, y endulza solo si hace falta. Sirve muy fría con hielo y, si quieres, hojas de menta.",
      image="img/secciones/lm-agua-sandia.jpg", ilustracion=True),
    p("lm-te-melocoton", "Té helado de melocotón",
      ["2 bolsitas de té negro", "1 l de agua", "1 melocotón maduro", "2 cucharadas de azúcar o miel", "zumo de 1/2 limón", "hielo"],
      "Infusiona el té en el agua caliente 4-5 minutos y deja enfriar. Tritura el melocotón con un poco de agua y mézclalo con el té, el endulzante y el limón. Sirve bien frío con hielo y láminas de melocotón.",
      image="img/secciones/lm-te-melocoton.jpg", ilustracion=True),
    p("lm-horchata", "Horchata de chufa",
      ["200 g de chufas secas", "1 l de agua", "100 g de azúcar", "ralladura de limón", "canela"],
      "Remoja las chufas en agua 12 horas, escúrrelas y tritúralas con el litro de agua. Deja reposar 1-2 horas y cuela con un paño exprimiendo bien. Endulza con el azúcar, perfuma con limón y canela y enfría. Sirve muy fría, removiendo antes.",
      image="img/secciones/lm-horchata.jpg", ilustracion=True),
    p("lm-mojito-sin", "Mojito sin alcohol",
      ["1 lima", "un puñado de hojas de menta", "2 cucharaditas de azúcar", "agua con gas", "hielo picado"],
      "Maja la lima en gajos con la menta y el azúcar en el fondo del vaso para soltar los aromas. Llena de hielo picado y completa con agua con gas. Remueve y decora con menta y lima.",
      image="img/secciones/lm-mojito-sin.jpg", ilustracion=True),
    p("lm-jamaica", "Agua de jamaica",
      ["30 g de flor de jamaica (hibisco) seca", "1 l de agua", "4 cucharadas de azúcar", "zumo de 1/2 limón", "hielo"],
      "Hierve el agua, retira del fuego y añade la flor de jamaica; deja infusionar 10-15 minutos. Cuela, endulza con el azúcar y añade el limón. Enfría y sirve con hielo.",
      image="img/secciones/lm-jamaica.jpg", ilustracion=True),
])

# ---------------------------------------------------------------------------
# MOMENTO DEL DÍA (filtro transversal): la sección agrupa por tipo de plato y
# el "momento" permite filtrar por desayuno/comida/cena/merienda/aperitivo/
# postre/guarnición. Defecto por sección + excepciones editoriales por plato.
# ---------------------------------------------------------------------------
MOMENTOS_SECCION = {
    "sopas-frias": ["comida", "cena"],
    "salsas": ["guarnicion"],
    "smoothies": ["desayuno", "merienda"],
    "comidas-proteicas": ["comida", "cena"],
    "pintxos": ["aperitivo", "cena"],
    "tostas": ["desayuno", "merienda", "aperitivo"],
    "aperitivos": ["aperitivo"],
    "ensaladas": ["comida", "cena"],
    "postres": ["postre", "merienda"],
    "dips": ["aperitivo"],
    "cremas-frias": ["comida", "cena"],
    "huevos": ["desayuno", "comida", "cena"],
    "rumanos": ["comida", "cena"],
    "croquetas": ["aperitivo", "comida", "cena"],
    "limonadas": ["merienda", "aperitivo"],
}
# Excepciones: platos dulces o de fruta que encajan mejor en merienda/postre, etc.
MOMENTOS_OVERRIDE = {
    "sm-chocolate": ["merienda", "postre"],
    "sm-sandia": ["merienda", "postre"],
    "ts-cabra-miel": ["aperitivo", "merienda"],
    "ts-brie-pera-nueces": ["aperitivo", "merienda"],
    "ts-ricotta-miel-nueces": ["desayuno", "merienda", "postre"],
    "ts-azul-higo": ["aperitivo", "merienda"],
    "en-frutas": ["merienda", "postre"],
    "en-verano": ["comida", "cena", "postre"],
}
for s in SECCIONES:
    for d in s["platos"]:
        d["momentos"] = MOMENTOS_OVERRIDE.get(d["id"], MOMENTOS_SECCION[s["id"]])

out = {
    "_nota": "Generado por build_secciones.py a partir de las infografías de 'imagenes comida/'. "
             "Maestro en español; la app calcula alérgenos y dietas desde los ingredientes. "
             "'momentos' es un filtro transversal por franja del día (no recategoriza la sección).",
    "secciones": SECCIONES,
}
json.dump(out, open("secciones.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)

total = sum(len(s["platos"]) for s in SECCIONES)
print(f"secciones.json escrito: {len(SECCIONES)} secciones, {total} platos")
for s in SECCIONES:
    print(f"  - {s['titulo']}: {len(s['platos'])}")
